/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.JavaGitHub;


import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Menu de Opciones");
        System.out.println("1. Validar Contraseña");
        System.out.println("2. Calcular Edad");
        System.out.println("3. Generar Contraseña Aleatoria");
        System.out.println("4. Determinar si un numero es PAR o IMPAR");
        System.out.println("5. Calculadora Dias de Vida");
        System.out.println("6. Generar Contraseña Personalizada");
        System.out.println("6. Calculadora Básica");
        System.out.println("Ingrese una Opcion");
        
        int opc = sc.nextInt();
        switch (opc){
            case 1:
                Sistema_Login();
                break;
            case 2:
                Calcular_Edad();
                break;
            case 3:
                Generar_Contrasena();
                break;
                //agregar mas case para los demas ejercicios 
            case 4:
                par_impar();
                break;
            case 5:
                CalculadoraDiasVida();
                break;
            case 6: 
                GenerarContrasenaPersonalizada(); 
                break;
            case 7: 
                CalculadoraBasica(); 
                break;
            default:
                System.out.println("Ingrese Una Opcion Valida");
        }
        
    }
    public static void Sistema_Login(){
        Scanner sc= new Scanner(System.in);
        String contraseña_valida = "Trabajo3105";
        int intentos = 3;
        while(intentos > 0){
            System.out.println("Ingrese la Contraseña");
            String contraseña = sc.nextLine();
            if (!contraseña.equals(contraseña_valida)) {
                intentos = intentos - 1 ;
            }
            else{
                System.out.println("Acceso Permitido");
                break;
            }
        }
        if (intentos == 0) {
            System.out.println("Acceso Denegdado");
        }
    }
    //Cada ejercicio crean en una nueva funcion
    
    public static void Calcular_Edad(){
        Scanner sc = new Scanner(System.in);
        
        System.out.println("=======================================");
        System.out.println("Ingrese su año de nacimiento:)");
        int anioNacimiento = sc.nextInt();
        System.out.println("=======================================");
        System.out.println("=======================================");
        System.out.println("muy bien");
        
        System.out.println("Ingrese su mes de nacimiento:");
        int mesNacimiento = sc.nextInt();
        
        int anioActual = 2026;
        int mesActual = 6;
        
        int edad = anioActual - anioNacimiento;
        
        if(mesNacimiento > mesActual){
            edad--;
        }
        
        System.out.println("Su edad es: " + edad + "años" );
    }

    public static void Generar_Contrasena(){
        String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        String contrasena = "";

        for(int i = 0; i < 10; i++){
            int indice = (int)(Math.random() * caracteres.length());
            contrasena += caracteres.charAt(indice);
        }

        System.out.println("Contraseña generada: " + contrasena);
    }
        public static void par_impar() {
        
        Scanner sc = new Scanner(System.in);
        //SI UN NUMERO ES IMPAR O PAR
        System.out.println("===============");
        System.out.println("PAR O IMPAR");
        System.out.println("Ingresa el NUMERO ");
        int numero= sc.nextInt();
       if (numero % 2 == 0) {
            System.out.println("El numero es par");
        } else {
            System.out.println("El numero es impar");
        }
            
        } 

}


    public static void  CalculadoraDiasVida() {

            Scanner scanner = new Scanner(System.in);

            System.out.print("Ingresa tu año de nacimiento: ");
            int ano = scanner.nextInt();

            System.out.print("Ingresa tu mes de nacimiento (1-12): ");
            int mes = scanner.nextInt();

            System.out.print("Ingresa tu día de nacimiento: ");
            int dia = scanner.nextInt();

            // Días aprox. por año y mes
            int anosVividos = 2026 - ano;
            int diasVividos = anosVividos * 365 + (mes - 1) * 30 + dia;

            System.out.println("\nHas vivido aproximadamente: " + diasVividos + " días");
            
            scanner.close();
             
        }
    //Generar una contraseña personalizada
    