/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.JavaGitHub;


import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Menu de Opciones");
        System.out.println("1. Validar Contraseña");
        System.out.println("Ingrese una Opcion");
        int opc = sc.nextInt();
        switch (opc){
            case 1:
                Sistema_Login();
                break;
                //agregar mas case para los demas ejercicios 
            default:
                System.out.println("Ingrese Una Opcion Valida");
        }
        
    }
    public static void Sistema_Login(){
        Scanner sc= new Scanner(System.in);
        String contraseña_valida = "Trabajo3105";
        int intentos = 3;
        while(intentos > 0){
            System.out.println("Ingrese la Contraseña");
            String contraseña = sc.nextLine();
            if (!contraseña.equals(contraseña_valida)) {
                intentos = intentos - 1 ;
            }
            else{
                System.out.println("Acceso Permitido");
                break;
            }
        }
        if (intentos == 0) {
            System.out.println("Acceso Denegdado");
        }
    }
    //Cada ejercicio crean en una nueva funcion
    
   
            
            
      
   
}