/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.JavaGitHub;


import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("algoritmo para cambiar el usuario y la contraseña con  confirmacion con ciclo while y con 3 intentos");
        System.out.println("el cambio debe hacer el sr achote");
        Scanner sc = new Scanner(System.in);
        System.out.println("Menu de Opciones");
        System.out.println("1. Validar Contraseña");
        System.out.println("2. Calcular Edad");
        System.out.println("3. Generar Contraseña Aleatoria");
        System.out.println("4. Determinar si un numero es PAR o IMPAR");
        System.out.println("5. Calculadora Dias de Vida");
        System.out.println("6. Generar Contraseña Personalizada");
        System.out.println("7. Calculadora Básica");
        System.out.println("8 Hola mundo");
        System.out.println("9 Tabla");
        System.out.println("Ingrese una Opcion");
        
        int opc = sc.nextInt();
        switch (opc){
            case 1:
                Sistema_Login();
                break;
            case 2:
                Calcular_Edad();
                break;
            case 3:
                Generar_Contrasena();
                break;
                //agregar mas case para los demas ejercicios 
            case 4:
                par_impar();
                break;
            case 5:
                CalculadoraDiasVida();
                break;
            case 6: 
                GenerarContrasenaPersonalizada(); 
                break;
            case 7: 
                CalculadoraBasica(); 
                break;
            case  8:
                hola();
            case 9:
                tabla();
            default:
                System.out.println("Ingrese Una Opcion Valida");
        }
        
    }
    public static void Sistema_Login() {
        Scanner sc = new Scanner(System.in);
        String usuario_valido = "Admin123";
        String contraseña_valida = "Trabajo3105";

        int intentosUsuario = 3;
        int intentosContraseña = 3;

        while (intentosUsuario > 0) {
            System.out.println("Ingrese el nombre de Usuario");
            String usuario = sc.nextLine();

            if (usuario.equals(usuario_valido)) {
                break; 
            } else {
                intentosUsuario--;
                if (intentosUsuario > 0) {
                    System.out.println("El ususario es incorrecto. Quedan " + intentosUsuario + " intentos.");
                }
            }
        }
        if (intentosUsuario == 0) {
            System.out.println("Acceso no permitido . Se a terminado todos los intentos  .");
            return;
        }

        while (intentosContraseña > 0) {
            System.out.println("Ingrese la Contraseña");
            String contraseña = sc.nextLine();

            if (contraseña.equals(contraseña_valida)) {
                System.out.println("Acceso Concedido ");
                return; 
            } else {
                intentosContraseña--;
                if (intentosContraseña > 0) {
                    System.out.println("Contraseña incorrecta. Te quedan " + intentosContraseña + " intentos.");
                }
            }
        }
        if (intentosContraseña == 0) {
            System.out.println("Acceso no permitido . Intentos de contraseña agotados.");
       }
}
    public static void tabla(){
            Scanner sc = new Scanner(System.in);
     //TABLA DE MULTIPLICAR
     System.out.println("===============");
     System.out.println("TRABLA DE MULTIPLICAR");
     System.out.println("Ingresa el numero de la tabla a mostrar: ");
     int num= sc.nextInt();
     System.out.println("\nTabla de multiplicar del " + num + ":");
     for (int i = 1; i <= 10; i++) {
     int resultado = num * i;
     System.out.println(num + " x " + i + " = " + resultado);
     } 

    }
    
    public static void hola(){
        System.out.println("Hola mundo");
    }
    //Cada ejercicio crean en una nueva funcion
    
    public static void Calcular_Edad(){
        Scanner sc = new Scanner(System.in);
        
        System.out.println("Ingrese su año de nacimiento:");
        System.out.println("hola");  
        int anioNacimiento = sc.nextInt();
        System.out.println("alex haces huevadas la plena hermano");
        System.out.println("jajajaja");
        
        System.out.println("Ingrese su mes de nacimiento:");
        int mesNacimiento = sc.nextInt();
        
        int anioActual = 2026;
        int mesActual = 6;
        
        int edad = anioActual - anioNacimiento;
        
        if(mesNacimiento > mesActual){
            edad--;
        }
        
        System.out.println("Su edad es: " + edad + "años" );
    }

    public static void Generar_Contrasena(){
        String caracteres = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        String contrasena = "";

        for(int i = 0; i < 10; i++){
            int indice = (int)(Math.random() * caracteres.length());
            contrasena += caracteres.charAt(indice);
        }

        System.out.println("Contraseña generada: " + contrasena);
    }
        public static void par_impar() {
        
        Scanner sc = new Scanner(System.in);
        //SI UN NUMERO ES IMPAR O PAR
        System.out.println("===============");
        System.out.println("PAR O IMPAR");
        System.out.println("Ingresa el NUMERO ");
        int numero= sc.nextInt();
       if (numero % 2 == 0) {
            System.out.println("El numero es par");
        } else {
            System.out.println("El numero es impar");
        }
            
        } 
            public static void  CalculadoraDiasVida() {

            Scanner scanner = new Scanner(System.in);

            System.out.print("Ingresa tu año de nacimiento: ");
            int ano = scanner.nextInt();
            System.out.println("hola mundo");
            System.out.println("Hola byron ");

            System.out.print("Ingresa tu mes de nacimiento (1-12): ");
            int mes = scanner.nextInt();
                System.out.println("hola mundo");

            System.out.print("Ingresa tu día de nacimiento: ");
            int dia = scanner.nextInt();

            // Días aprox. por año y mes
            int anosVividos = 2026 - ano;
            int diasVividos = anosVividos * 365 + (mes - 1) * 30 + dia;

            System.out.println("\nHas vivido aproximadamente: " + diasVividos + " días");
            
            scanner.close();
        }
    //Generar una contraseña personalizada

    /**
     *
     */
    public static void GenerarContrasenaPersonalizada() {
        Scanner sc = new Scanner(System.in);
        
        System.out.print("Longitud de la contraseña (8-20): ");
        int longitud = sc.nextInt();
        if(longitud < 8) longitud = 8;
        if(longitud > 20) longitud = 20;
        
        System.out.print("¿Incluir números? (si/no): ");
        boolean numeros = sc.next().equalsIgnoreCase("si");
        
        System.out.print("¿Incluir símbolos? (si/no): ");
        boolean simbolos = sc.next().equalsIgnoreCase("si");
        
        String base = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        if(numeros) base += "0123456789";
        if(simbolos) base += "!@#$%^&*()_+-=";
        
        String contrasena = "";
        for(int i = 0; i < longitud; i++){
            int indice = (int)(Math.random() * base.length());
            contrasena += base.charAt(indice);
        }
        
        System.out.println("Contraseña generada: " + contrasena);
    }

    public static void CalculadoraBasica() {
        Scanner sc = new Scanner(System.in);
        System.out.print("Primer número: ");
        double a = sc.nextDouble();
        System.out.print("Segundo número: ");
        double b = sc.nextDouble();
        
        System.out.println("1.Sumar  2.Restar  3.Multiplicar  4.Dividir");
        int op = sc.nextInt();
        
        switch (op) {
            case 1:
                System.out.println("Resultado: " + (a + b));
                break;
            case 2:
                System.out.println("Resultado: " + (a - b));
                break;
            case 3:
                System.out.println("Resultado: " + (a * b));
                break;
            case 4:
                if (b != 0) {
                    System.out.println("Resultado: " + (a / b));
                } else {
                    System.out.println("No se puede dividir por cero");
                }    break;
            default:
                System.out.println("Opción no válida");
                break;
        }
        }
}




